name: Build and Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Set timestamp environment variable
        run: echo "BANNER_EXPIRY=$(date +%s)" >> "$GITHUB_ENV"
      - name: Build
        run: npm run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          VITE_BANNER_EXPIRY: '${{ env.BANNER_EXPIRY }}'
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy:
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
